/*
 * config_nucleo.h
 *
 *  Created on: Dec 10, 2015
 *      Author: Bumsik Kim
 */

#ifndef CONFIG_NUCLEO_H_
#define CONFIG_NUCLEO_H_

#ifdef NUCLEO_F466RE

#ifndef LED_PIN
	#define LED_PIN GPIO_PIN_5
	#define LED_PORT GPIOA
#endif

#ifdef USE_HAL_DRIVER
	#ifdef LED_PIN
		#ifdef LED_PORT
			#define LED_TOGGLE()	HAL_GPIO_TogglePin(LED_PORT, LED_PIN)
			#define LED_ON()		HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_SET)
			#define LED_OFF()		HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_RESET)
		#endif
	#endif
#endif

/* Pin definitions generated by CubeMX */
#define B1_Pin GPIO_PIN_13
#define B1_GPIO_Port GPIOC
#define USART_TX_Pin GPIO_PIN_2
#define USART_TX_GPIO_Port GPIOA
#define USART_RX_Pin GPIO_PIN_3
#define USART_RX_GPIO_Port GPIOA
#define LD2_Pin GPIO_PIN_5
#define LD2_GPIO_Port GPIOA
#define TMS_Pin GPIO_PIN_13
#define TMS_GPIO_Port GPIOA
#define TCK_Pin GPIO_PIN_14
#define TCK_GPIO_Port GPIOA
#define SWO_Pin GPIO_PIN_3
#define SWO_GPIO_Port GPIOB

#endif

#endif /* CONFIG_NUCLEO_H_ */
