.all:

.PHONY: all welcome

all: welcome
	@echo ""
	@exit 1

welcome:
	@echo "Welcome to Wolfiemouse firmware directory!"
	@echo ""
	@echo "You should run 'make' in application's directory instead."
	@echo "    e.g. blinky_nucleo64"
	@echo ""
	@echo "For more information, please look at README.md."
